### PR TITLE
moved old sketch UI file into an archive to reduce confusion

### PR DESCRIPTION
**Pull request by phiden**
Added V2 to master already; moving the original into an archive

### CODE REVIEW

**Comment by line47** [comment]
I'm a bit unsure about naming the Sketch file V2. I think it's easier to keep the name as it is. 

I'm recommending that we remove the V2 from the file name and keep it as `CMS Design System UI kit.sketch` and don't keep an archived file at all.

**Comment by phiden** [comment]
Happy to rename it, but want to keep the old one for the record.

**Comment by line47** [comment]
Github will keep it in history for us so we don't have to 👍 
For example - https://github.com/CMSgov/design-system/commits/master/design-assets

**Comment by line47** [comment]
I'm so excited this work is happening! 🚀

**Comment by phiden** [comment]
> Github will keep it in history for us so we don't have to 👍
> For example - https://github.com/CMSgov/design-system/commits/master/design-assets

Right, but not everyone is familiar with Github, and this may make it harder to find if someone is interested.

**Comment by line47** [comment]
I'm unsure as to why someone would want to use the old version - if you feel strongly about keeping it that works for me?

**Comment by phiden** [comment]
> I'm unsure as to why someone would want to use the old version - if you feel strongly about keeping it that works for me?

Yeah, I do. It's happened before. We can revisit it at a later point.

**Pull request merged**
