### PR TITLE
[WNMGDS-1445] updating link styles for active and focus state

### PR DESCRIPTION
**Pull request by scheul93**
## Summary

Having background of link element be transparent when link has active & focus states.

[Bug report in Jira](https://jira.cms.gov/browse/WNMGDS-1445)

## How to test

- Navigate to the [demo storybook site](http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-1445/inverse-link-style-updates/core/storybook/?path=/story/typography-links--links)
- View link stories at Typography > Links
- For the inverse link example, click & hold your cursor on the link (this creates an active & focus state). Confirm that the background color is transparent and meets accessibility expectations
  - Alternatively, using dev tools, you can select an element in the the `elements` tab. Click the 3 dots to the left, go to 'focus state' and toggle on active & focus to see the reported state

## Questions for Designers
- Is this the expected styling for a link in this state?
- Are there any accessibility  or other concerns that need to be taken into account?

### CODE REVIEW

**Review by line47 — APPROVED** [review]
This looks good to me, thanks Anna!

**Comment by line47** [comment]
@ericwbailey can you capture this in a ticket maybe for a system wide approach to active states? 

> What do you all think about using white? I like active states to have a "pressed" feel, and it would mirror our approach for the on light link treatment.

**Comment by ericwbailey** [comment]
@line47 Sure thing, I'll write one up now.

**Comment by ericwbailey** [comment]
Ticket is here: [WNMGDS-1473](https://jira.cms.gov/browse/WNMGDS-1473).

**Pull request merged**
