### PR TITLE
[LHDM-1818] Pass backdropClickExits to NativeDialog from Drawer

### PR DESCRIPTION
**Pull request by seesleestak**
## Summary

- Passing `backdropClickExits` to `NativeDialog` from `Drawer` to allow usage of the prop from `Drawer`/`HelpDrawer`. These changes are to support requests from stakeholders to implement a drawer similar to Medicare.gov's (with its modified functionality). Our team has currently patched in this change in order to move ahead with that implementation.
- https://jira.cms.gov/browse/LHDM-1818

## How to test

1. `yarn storybook`
2. Value for `backdropClickExits` and `hasFocusTrap` props allows the behavior in the `Drawer` [example](http://localhost:6006/?path=/story/components-drawer--drawer-toggle-with-drawer).

## Checklist

- [x] Prefixed the PR title with the [Jira ticket number](https://jira.cms.gov/projects/WNMGDS/) as `[WNMGDS-####] Title` or [NO-TICKET] if this is unticketed work.
- [x] Selected appropriate `Type` (only one) label for this PR, if it is a breaking change, label should only be `Type: Breaking`
- [x] Selected appropriate `Impacts`, multiple can be selected.

### If this is a change to code:

- [ ] Created or updated unit tests to cover any new or modified code
- [x] If necessary, updated unit-test snapshots (`yarn test:unit:update`) and browser-test snapshots (`yarn test:browser:update`)

### If this is a change to documentation:

- [x] Checked for spelling and grammatical errors

### CODE REVIEW

**Comment by seesleestak** [comment]
@pwolfert Just wanted to bump this PR for possible inclusion in v12. Having this change would allow us to [remove one of our patches](https://github.cms.gov/CMS-WDS/learn-frontend-gatsby/blob/main/patches/%40cmsgov%2Bdesign-system%2B7.0.2.patch).

**Comment by pwolfert** [comment]
@seesleestak, I know the patches aren't a pretty thing, but we're not yet ready to merge this until we get a final word about the pattern from our stakeholders. We'll continue to discuss this.

**Comment by seesleestak** [comment]
Understood, thanks for the update

**Comment by seesleestak** [comment]
Hey there, I wanted to follow up on this change. Has any determination been made about it?

**Comment by seesleestak** [comment]
👀 
Thanks for making the required storybook updates 👍  Is this able to be merged whenever or do you need me to hold off?

**Comment by pwolfert** [comment]
Go ahead and merge it, @seesleestak! You're clear to launch.

**Pull request merged**
