### PR TITLE
[WNMGDS-2235] Fix, updates error-light to error-lighter for medicare, checking in token changes made in previous 2235 PR

### PR DESCRIPTION
**Pull request by forrestbaer**
## Summary

- Tokens needed updating after last 2235 PR. #2394 
- Medicare inverse error color was `error-light` and needed to be `error-lighter`

## Checklist

- [x] Prefixed the PR title with the [Jira ticket number](https://jira.cms.gov/projects/WNMGDS/) as `[WNMGDS-####] Title` or [NO-TICKET] if this is unticketed work.
- [x] If necessary, updated unit-test snapshots (`yarn test:unit:update`) and browser-test snapshots (`yarn test:browser:update`)

### CODE REVIEW

**Comment by forrestbaer** [comment]
I would like to merge this before submitting a PR for the VRT changes.

**Comment by line47** [comment]
When I view the monthpicker for Medicare in storybook running locally I see a text color of #e8b3b3 and a background color of #146a5d are you sure this is for Medicare and not Healthcare?

**Comment by line47** [comment]
I think we might need to change the error text color to use `error-lightest` to pass contrast

**Comment by forrestbaer** [comment]
The a11y logs are really unhelpful in pinpointing where the problem shows up, I'll see what I can find out locally

**Comment by forrestbaer** [comment]
Those errors were all from core, I've updated cores error as well to error-light and it seems to have resolved it... It looks like there is one snapshot change that appears to be an error, I say we ignore this for now as my next PR with be making a bunch of snapshot updates.

**Comment by pwolfert** [comment]
`tests/browser/snapshots/foundations-typography-headings--heading-2-xl-healthcare--firefox.png` do you know why was changed?

**Comment by forrestbaer** [comment]
Yes I'm tracking that in the next PR

**Comment by forrestbaer** [comment]
As a note I've discovered this is related to firefox not cooperating with playwright occasionally, in the new branch I'm testing with an upgrade to playwright (1.30.0 -> 1.31.0) which might resolve it.

**Pull request merged**
