### PR TITLE
[WNMGDS-2884] Add `cmsds-migrate` script for v11 CSS changes

### PR DESCRIPTION
**Pull request by pwolfert**
## Summary

In order to reduce the risk for teams upgrading, I've added a `cmsds-migrate` script that will flag or replace references to things we're deprecating in v11.

Through creating this, I also found that our release notes are wrong, and we didn't remove `--font-weight-bold` and `--font-weight-normal`, nor did we intend to.

## How to test

1. Run `yarn cmsds-migrate`
2. Select the top `deprecated css v11` script
3. Choose yes
4. Take a look at the changed files and then discard changes. We expect it to flag historical references to some of those and to find references in the deprecation CSS. I don't think in production it'll flag references in the cmsds-migrate script itself. That's an area for improvement though.
5. You can try creating references to some of the removed or renamed things in the examples or elsewhere in the code and see if the script picks them up.

## Checklist

- [x] Prefixed the PR title with the [Jira ticket number](https://jira.cms.gov/projects/WNMGDS/) as `[WNMGDS-####] Title` or [NO-TICKET] if this is unticketed work.
- [x] Selected appropriate `Type` (only one) label for this PR, if it is a breaking change, label should only be `Type: Breaking`
- [x] Selected appropriate `Impacts`, multiple can be selected.
- [x] Selected appropriate release milestone

### CODE REVIEW

**Review by jack-ryan-nava-pbc — APPROVED** [review]
Works locally as expected and looks good! One thing I'm wondering is if it would be easier to make the selections easier to discern/read using capitalization? That would be a change to the main script rather than here.

**Comment by pwolfert** [comment]
There's certainly room for improvement in the script, but it's out of scope here

**Comment by pwolfert** [comment]
I've added an update to the blog post that calls the migration script out and includes an info alert explaining how to use it. Let me know what you think about that.

**Review by jack-ryan-nava-pbc — APPROVED** [review]
LGTM

**Pull request merged**
