### PR TITLE
[WNMGDS-2480] fix mgov footer layout

### PR DESCRIPTION
**Pull request by zarahzachz**
WNMGDS-2480

- Fix mobile layout so footer content stacks in the same order it appears in DOM
- Refactored CSS to remove complex styles, media queries; rely on grid to accomplish layout

[demo url](https://cmsgov.github.io/design-system/branch/WNMGDS-2480/update-mobile-view-of-mgov-footer)

### CODE REVIEW

**Review by pwolfert — APPROVED** [review]
Looks really good to me. Everything lines up better and looks cleaner. I'm not 100% sure what all the breakpoints are supposed to look like, so @brentschneider will have to approve those.

**Comment by brentschneider** [comment]
Is there a demo link or should I build this locally?

**Review by brentschneider — APPROVED** [review]
@zarahzachz Overall looking great to me but I'll defer to @hi-its-hailey for her review.  
  
Question about the Medicare and HHS logos not following the same pattern as Healthcare.gov and CMS.gov linking to their perspective locations. Do we know if that was deliberate decision made or an oversight missed by the team reproducing our unified footer.

**Comment by zarahzachz** [comment]
> Do we know if that was deliberate decision made or an oversight missed by the team reproducing our unified footer.

no idea, i just went off melissa's decision in slack to address the stacking issue. our footer code is very old (its been this way at least since i joined ad hoc 2 yrs ago).

**Review by hi-its-hailey — APPROVED** [review]

**Comment by hi-its-hailey** [comment]
Looks good to me! Thank you @zarahzachz 
Looks like you have the HHS logo stay on the same line as "Medicare.gov" -- is it likely that most mobile breakpoints will accommodate this?

And yeah, @brentschneider, Krithi and Melissa went back and forth on the HHS logo, but the final call was to hold off for now to prevent any impact to assumptions listed on the confluence page. It sounds like she is down to remove the logo later on though.

**Pull request merged**
