### PR TITLE
[WNMGDS-2835] Adds figma links to docs site

### PR DESCRIPTION
**Pull request by kim-cmsds**
## Summary
- JIRA link: https://jira.cms.gov/browse/WNMGDS-2835
- Removes links to sketch assets on the docs site and replaces those with links to figma pages based on whichever theme is currently in use

## How to test

1. This branch can either be pulled down locally or viewed at https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/
2. Go through each updated docs site page using each theme (cmsgov, core, healthcare, medicare) and click the figma link and verify that the figma page corresponds with the docs site page content

- [x] [accordion](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/accordion)
- [x] [accordion](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/accordion)
- [x] [alert](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/alert)
- [x] [autocomplete](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/autocomplete)
- [x] [badge](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/badge)
- [x] [button](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/button)
- [x] [card](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/card)
- [x] [checkbox](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/checkbox)
- [x] [date-picker](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/date-field/date-picker)
- [x] [multi-input-date-field](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/date-field/multi-input-date-field)
- [x] [single-input-date-field](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/date-field/single-input-date-field)
- [x] [drawer](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/drawer)
- [x] [dropdown](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/dropdown)
- [x] [filter-chip](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/filter-chip)
- [x] [healthcare-footer](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/footer/healthcare-footer)
- [x] [medicare-footer](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/footer/medicare-footer)
- [x] [healthcare-header](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/header/healthcare-header)
- [x] [medicare-header](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/header/medicare-header)
- [x] [icon](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/icon)
- [x] [healthcare-logo](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/logos/healthcare-logo)
- [x] [hhs-logo](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/logos/hhs-logo)
- [x] [medicare-logo](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/logos/medicare-logo)
- [x] [modal-dialog](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/modal-dialog)
- [x] [month-picker](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/month-picker)
- [x] [pagination](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/pagination)
- [x] [radio](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/radio)
- [x] [review](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/review)
- [x] [skip-nav](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/skip-nav)
- [x] [spinner](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/spinner)
- [ ] [stars](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/stars)
- [x] [step-list](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/step-list)
- [x] [table](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/table)
- [x] [tabs](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/tabs)
- [x] [text-field/text-field](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/text-field/text-field)
- [x] [tooltip](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/tooltip)
- [x] [usa-banner](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/usa-banner)
- [x] [vertical-navigation](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/components/vertical-navigation)
- [ ] [layout-grid](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/foundation/layout-grid/layout-grid)
- [x] [spacing](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/foundation/spacing)
- [x] [body](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/foundation/typography/body)
- [x] [headings](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/foundation/typography/headings)
- [x] [links](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/foundation/typography/links)
- [x] [lists](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/foundation/typography/lists)
- [ ] [one-col-page-layout](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/layouts/Healthcare/one-col-page-layout)
- [x] [documentation-page](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/layouts/documentation-page)
- [x] [error-validation](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/patterns/Forms/error-validation)
- [x] [measure](https://cmsgov.github.io/design-system/branch/kniedermaier/WNMGDS-2835-update-docs-site/utilities/text/measure)

## Checklist

- [x] Prefixed the PR title with the [Jira ticket number](https://jira.cms.gov/projects/WNMGDS/) as `[WNMGDS-####] Title` or [NO-TICKET] if this is unticketed work.
- [x] Selected appropriate `Type` (only one) label for this PR, if it is a breaking change, label should only be `Type: Breaking`
- [x] Selected appropriate `Impacts`, multiple can be selected.
- [x] Selected appropriate release milestone

### CODE REVIEW

**Comment by jack-ryan-nava-pbc** [comment]
I am experiencing some strange behavior that is going to be tricky to convey verbally, but here goes.
Seems like the theme switcher is not properly changing the Figma library link when the theme is changed. The theme is changed properly on initial page load, but the theme switcher sets the url back to the generic Design System link instead of the theme specific link.

Steps to reproduce:

1. Select the `alert` component with the Core theme chosen
2. Open the Figma library in your local instance of Figma desktop (not browser Figma)
3. You'll be sent to the Design System Library - okey dokey
4. Change theme from Core to Medicare
5. Open Figma
6. Still sent to Design System Library - hmm
7. Leave Medicare theme selected
8. Go to `autocomplete` component page then back to the `alert` component page
9. Open Figma
10. Sent to Medicare specific Figma library - ok, but hmm?
11. Switch theme to Healthcare or CMS
12. Open Figma
13. Go to Design System library?

**Comment by tamara-corbalt** [comment]
@jack-ryan-nava-pbc, I was able to replicate this:

> I am experiencing some unexpected behavior that is going to be tricky to convey verbally, but here goes. Seems like the theme switcher is not properly changing the Figma library link when the theme is changed. The theme is changed properly on initial page load, but the theme switcher sets the url back to the generic Design System link instead of the theme specific link.
> 
> Steps to reproduce:
> 
> 1. Select the `alert` component with the Core theme chosen
> 2. Open the Figma library in your local instance of Figma desktop (not browser Figma)
> 3. You'll be sent to the Design System Library - okey dokey
> 4. Change theme from Core to Medicare
> 5. Open Figma
> 6. Still sent to Design System Library - hmm
> 7. Leave Medicare theme selected
> 8. Go to `autocomplete` component page then back to the `alert` component page
> 9. Open Figma
> 10. Sent to Medicare specific Figma library - ok, but hmm?
> 11. Switch theme to Healthcare or CMS
> 12. Open Figma
> 13. Go to Design System library?

Additional steps I followed:
14. Left the Healthcare theme selected, and navigated to the Autocomplete page then back to the alert component page.
15. Opened Figma link, was sent to the Healthcare specific Figma library.

Could this point towards a caching issue or a missed update in the theme-switching logic?

**Comment by kim-cmsds** [comment]
@tamara-corbalt and @jack-ryan-nava-pbc I think this is an issue with gatsby when deployed with `gh-pages`.

If you go to another branch that is deployed with `gh-pages` (https://cmsgov.github.io/design-system/branch/pwolfert/release-11-blog-post/components/alert/?theme=medicare) and follow the same step series (more or less) then you'll notice that the sketch link is not updating based on the theme switcher.

I was not able to reproduce this locally or on the production site.

**Review by malloryiden — DISMISSED** [review]
Whew, this was a doozy! Looks awesome, and thank you for all the direct links to your branch to review with, it made it very easy. A few notes:

**Stars**
Core: Figma link missing
CMS: Figma links to design system "figma setup"
HC: No figma link
MC: Correct ✅ 

**Layout Grid**
No figma links for any product theme.

**One column page layout**
Figma link only included for hc.gov

**Comment by kim-cmsds** [comment]
@malloryiden thank you for the thorough review! I'm re-requesting your review for those 3 components you pointed out:
- stars
- layout grid
- one column grid layout

**Comment by kim-cmsds** [comment]
@tamara-corbalt and @jack-ryan-nava-pbc: I pushed up changes that should resolve the issues you pointed out

**Review by tamara-corbalt — APPROVED** [review]

**Pull request merged**
