### PR TITLE
Internal: Add prettier and precommit hook

### PR DESCRIPTION
**Pull request by sawyerh**
### Internal

There's a lot here, but it's mostly cosmetic changes to files that were made by running `prettier`. **[View this for a more focused comparison of what's actually been added/changed.](https://github.com/CMSgov/design-system/compare/staging...9b0a498)**

- Prettier runs over changed code on commit
- Eslint runs over changed code on commit with `--fix`
- Changed to running `eslint` using the CLI rather via Gulp

### CODE REVIEW

**Comment by sawyerh** [comment]
Any objections to adding Prettier?

**Comment by pwolfert** [comment]
I've no objections. It'll make development that much faster.

**Comment by sawyerh** [comment]
Just holding off for #152 to be merged so I can resolve all conflicts at once.

**Comment by pwolfert** [comment]
Eh, sorry. I've got some time today. I'll finish that up

**Pull request merged**
