### PR TITLE
Consolidate npm packages

### PR DESCRIPTION
**Pull request by bernardwang**
### Summary
- [WNMGDS-317] Deprecate support & layout packages (#628) 
- [WNMGDS-286] Remove deprecated items (#635)
- [WNMGDS-389] Add migration info to doc site (#650) 
- [NO TICKET] v4 documentation changes (#652) 
- [WNMGDS-394] Add design-system-scripts package with build script (#651)

### CODE REVIEW

**Comment by bernardwang** [comment]
hmm im not sure why the e2e tests are failing... it runs fine locally for me

**Comment by bernardwang** [comment]
Hm, when you do a fresh install (removing `node_modules`) we're getting this error:
`Can't add "@cmsgov/design-system": invalid package version "".`

Weird thing is when you run `yarn install` a second time the error goes away. Currently this error is preventing travis from passing

**Comment by line47** [comment]
I can confirm the exact issue above of running `yarn install` twice. 

I am not getting any errors when running e2e tests though 🎉

**Comment by line47** [comment]
Nice, this is working for me, great job! 👍

**Pull request merged**
