### PR TITLE
[WNMGDS-2112] Add accent colors to themes

### PR DESCRIPTION
**Pull request by line47**
## Summary

- Added tokens for --color-accent-primary for all themes
- Updated doc site page to add color swatches for  --color-accent-primary
- Added styles for using --color-accent-primary for background colors
- **Did not** add accent color for text-color utilities at this time b/c I don't think it would be needed 

## How to test

1. Run doc site with `yarn start` and visit the theme file page to see accent color content on the page
2. Then visit the background color page to see the bg color examples 

## Checklist

- [x] Prefixed the PR title with the [Jira ticket number](https://jira.cms.gov/projects/WNMGDS/) as `[WNMGDS-####] Title` or [NO-TICKET] if this is unticketed work.
- [x] Selected appropriate `Type` (only one) label for this PR, if it is a breaking change, label should only be `Type: Breaking`
- [x] Selected appropriate `Impacts`, multiple can be selected.

### If this is a change to code:

- [ ] Created or updated unit tests to cover any new or modified code
- [ ] If necessary, updated unit-test snapshots (`yarn test:unit:update`) and browser-test snapshots (`yarn test:browser:update`)

### If this is a change to documentation:

- [ ] Checked for spelling and grammatical errors

### CODE REVIEW

**Review by pwolfert — APPROVED** [review]
LGTM, but one question: Why is it called `accent-primary` instead of just `accent`?

**Review by forrestbaer — APPROVED** [review]

**Comment by line47** [comment]
@pwolfert I was envisioning a future state where more than one accent color exists - open to other ways to handle this?

**Comment by pwolfert** [comment]
@line47, I would just hate to make it longer than needed if we don't plan on adding more, but it'd also be a breaking change to change it after we've released it. If there are others, what if the primary one was assumed primary so it's like `color-accent`, `color-accent-secondary`, etc? It's your call.

**Comment by line47** [comment]
I'd like to stick with the more explicit and future proof `color-accent-primary`

**Pull request merged**
