### PR TITLE
[WNMGDS-309] Create flex utilities

### PR DESCRIPTION
**Pull request by bernardwang**
### Added
- `.ds-u-flex-direction-[]` utility and documentation

### Changed
- Updated the flex-wrap documentation

### CODE REVIEW

**Comment by line47** [comment]
This looks good 👍 
I know this wasn't in the original ticket but do you think we should add the `Format ` and `Responsive format `

**Comment by bernardwang** [comment]
@line47 Are you talking about adding to [this section](https://gyazo.com/7bffd974322eefff3be75560e5f3df54)? Currently none of those "Responsive" sections show format because they are already included under each specific utility. I.e. in Flexbox there are 4 different utilities/formats, so I'm not sure it's possible to include a single format for a general responsive flexbox section.

**Comment by line47** [comment]
Ah yeah, that makes sense, maybe what I'm thinking is that there isn't any explanation of what type of breakpoint styling is happening there or what to expect. 

The styling used in the example is `ds-u-sm-justify-content` so maybe we say that above the example so folks know?

**Comment by bernardwang** [comment]
Ah I see. Given that thats a change that would have to be made across many pages (none of the responsive examples do that I believe), would you be ok with leaving that for another ticket?

**Comment by bernardwang** [comment]
Giving it some more thought, we also already link to the [breakpoints page](http://localhost:3000/guidelines/responsive/) on every responsive example, and the code is always available for people to see. Since the main goal of the responsive examples is to show the styles changing with different breakpoints, I could also see the argument that its not a huge priority to expose the utility classes.

**Pull request merged**
