### PR TITLE
[WNMGDS-786] Replace Travis CI build with Github Actions

### PR DESCRIPTION
**Pull request by bernardwang**
### Summary 
- Replace Travis with Github Actions

### How to test
- Click the checks tab to see the tests run
- Review the github actions yaml

### CODE REVIEW

**Comment by line47** [comment]
This is great! Do we need to also update the build passing shield on the README? 
https://github.com/CMSgov/design-system/edit/master/README.md

**Comment by bernardwang** [comment]
@line47 done!

**Review by line47 — APPROVED** [review]

**Comment by nichia** [comment]
This looks great! So to understand the process, do we need to click on the `check` after creating a PR or would that be done automatically by gitaction?

**Comment by line47** [comment]
I believe it will automatically run

**Pull request merged**
