### PR TITLE
[WNMGDS-1610] Add analytics-logging controls to Storybook

### PR DESCRIPTION
**Pull request by pwolfert**
## Summary

For https://jira.cms.gov/browse/WNMGDS-1610, I wanted to have an easy way for people to test out analytics, so I've added a control menu to Storybook for turning analytics mocking on and off.

## How to test

1. `yarn storybook`
2. Go to the Dialog story
3. Click on the little bell icon in the toolbar and turn on analytics logging
    Screen Shot 2022-04-29 at 2 56 15 PM
4. Open and close the dialog, and see the events logged to the browser's JavaScript console

### CODE REVIEW

**Comment by line47** [comment]
Hey @pwolfert I'm curious about what icons are available for use in the toolbar? Is there a list somewhere?

**Comment by pwolfert** [comment]
@line47, I was not able to find a reference list anywhere, so the way I found them was to look in their source code: https://github.com/storybookjs/storybook/blob/main/lib/components/src/icon/icons.tsx. I just read through that guess and tested ones that sounded good.

**Comment by pwolfert** [comment]
@line47, feel free to try different icons or ask me to try a specific one if you have ideas.

**Comment by pwolfert** [comment]
Here is `rss`:
Screen Shot 2022-05-02 at 9 25 02 AM


Here is `graphline`:
Screen Shot 2022-05-02 at 9 26 32 AM

**Comment by pwolfert** [comment]
Changed it to `graphline`

**Comment by scheul93** [comment]
I'm not seeing the analytics toggle doing anything...? When I click it to try to toggle it on, nothing changes and I don't see any logs in the console. What am I missing?
StorybookAnalytics

**Review by scheul93 — APPROVED** [review]
Works! If you click the correct buttons

**Comment by pwolfert** [comment]
I wrote the options that way to get around the problem of not having any context within the drop-down menu for what the icons are about besides the icon and hovering over it. If anyone has ideas for improving the experience in the future, have at it! For now, I'm going to merge this so we have the functionality.

**Pull request merged**
