### PR TITLE
[NO-TICKET] Add link variables to link page

### PR DESCRIPTION
**Pull request by line47**
## Summary

- Add link variables to link page

## How to test

1. Run `yarn start` and visit the link page and see that the variables are listed under the styles section

## Checklist

- [ ] Prefixed the PR title with the [Jira ticket number](https://jira.cms.gov/projects/WNMGDS/) as `[WNMGDS-####] Title`

### If this is a change to code:

- [ ] Created or updated unit tests to cover the logic added
- [ ] If necessary, updated unit-test snapshots (`yarn test:unit:update`) and browser-test snapshots (`yarn test:browser:update`)

### If this is a change to documentation:

- [ ] Checked for spelling and grammatical errors

### CODE REVIEW

**Comment by line47** [comment]
One odd thing that I noticed was that the names/values didn't match the values that I saw in the theme code?

**Comment by pwolfert** [comment]
Ah, the color names thing is a limitation stemming from how we store the tokens. Only the final hex value is what's stored in the variables (not the named colors), which means we have to look through the named variables and find the first match for that given hex value. In this case `coolblue-light` is a duplicate of `secondary` but comes first in the list. @line47

**Comment by line47** [comment]
Given our discussion earlier today about color and `coolblue` colors. I'm hesitant to push this update until that is resolved unless there is some sort of workaround. :thinking:

**Comment by pwolfert** [comment]
The only workaround I can think of is to remove `cooblue` 😆

**Comment by line47** [comment]
That's what I thought, maybe we could stange this work somewhere then as part of the breaking change to remove `coolblue` ?

**Review by forrestbaer — APPROVED** [review]

**Pull request merged**
