### PR TITLE
Update reference photos from v3.2.0

### PR DESCRIPTION
**Pull request by bernardwang**

### CODE REVIEW

**Comment by line47** [comment]
The only issue im seeing is that https://design.cms.gov/utilities/ exists on the live site and the utilities page URL has been updated to `/utilities/overview/` locally.

**Comment by line47** [comment]
Do we want to update backtop.json for the new url for `/utilities/overview/` ?

**Comment by bernardwang** [comment]
@line47 Nice catch! What do you think about me updating backstop.json to use `/utilities/overview/` for both reference and local url? This way next release it will just be a simple `backstop reference` to get everything to pass again and we won't need to re update `backstop.json`.

The reason why its failing now is because https://github.com/CMSgov/design-system/pull/498 was merged before this one, and this backstop.json change should have been in that PR.

**Comment by line47** [comment]
That sounds great, thanks!

**Comment by line47** [comment]
I'm still getting errors when trying to run `backstop test`

```
  throw er; // Unhandled 'error' event
      ^

Error: Stream not writable
    at module.exports.ChunkStream.write (/usr/local/lib/node_modules/backstopjs/node_modules/node-resemble-js/node_modules/pngjs/lib/chunkstream.js:46:24)
    at exports.PNG.PNG.write (/usr/local/lib/node_modules/backstopjs/node_modules/node-resemble-js/node_modules/pngjs/lib/png.js:92:16)
    at ReadStream.ondata (_stream_readable.js:667:20)
    at ReadStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ReadStream.Readable.push (_stream_readable.js:220:10)
    at lazyFs.read (internal/fs/streams.js:181:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:463:17)
Emitted 'error' event at:
    at exports.PNG.onerror (_stream_readable.js:691:12)
    at exports.PNG.emit (events.js:189:13)
    at module.exports.emit (events.js:189:13)
    at module.exports.ChunkStream.write (/usr/local/lib/node_modules/backstopjs/node_modules/node-resemble-   See: /Users/scottweber/Documents/github/design-system/tools/backstop_data/bitmaps_test/20191014-140649/failed_diff_backstop_default_CMSDS_-_Utilities_-_Measure_0_document_2_desktop.png
js/node_modules/pngjs/lib/chunkstream.js:46:10)
    at exports.PNG.PNG.write (/usr/local/lib/node_modules/backstopjs/node_modules/node-resemble-js/node_modules/pngjs/lib/png.js:92:16)
    [... lines matching original stack trace ...]
    at ReadStream.Readable.push (_stream_readable.js:220:10)
```

**Pull request merged**
