### PR TITLE
[NO-TICKET] Adds optional bundle analysis to the build command

### PR DESCRIPTION
**Pull request by pwolfert**
## Summary

- Adds optional bundle analysis to the build command like `yarn build:core --analyze-bundles`

## How to test

`yarn build:core --analyze-bundles` and open the html files it generates

### CODE REVIEW

**Comment by jack-ryan-nava-pbc** [comment]
Works like a charm. I haven't looked too deeply into this package, but is it possible for it to give us a size other than the stat/pre-tree shaken size of the packages? All the `parse` and `gzip` values report 0kb, which seems incorrect?

**Comment by pwolfert** [comment]
There's a `defaultSizes` option, and I wondered if changing it to `gzip` would force it to collect that data, but it didn't work. I'm not sure why that data is missing.

**Comment by pwolfert** [comment]
Oh, there's [this troubleshooting note](https://www.npmjs.com/package/webpack-bundle-analyzer#troubleshooting)

**Review by kim-cmsds — APPROVED** [review]
This works locally with the various child design system packages! And let's go with `--analyze-bundles`.

**Review by jack-ryan-nava-pbc — APPROVED** [review]

**Pull request merged**
