### PR TITLE
[WNMGDS-2291] Fix doc site mobile navigation

### PR DESCRIPTION
**Pull request by pwolfert**
## Summary

https://jira.cms.gov/browse/WNMGDS-2291

Fixes the mobile navigation, which we forgot to take into account [when updating the doc site nav menu to fix a color contrast issue](https://github.com/CMSgov/design-system/pull/2452).

## How to test

1. Try out the navigation panel for the doc site on desktop and mobile

### CODE REVIEW

**Comment by zarahzachz** [comment]
This looks good but I'm noticing the switchers have a max-width, which might look funny on tablets.

Screenshot 2023-04-24 at 9 55 36 AM

**Review by zarahzachz — APPROVED** [review]
Approving - our form elements have a max-width so the tablet issue might not be something we want to fix and USA banner missing is an unrelated issue.

**Comment by pwolfert** [comment]
Oh, I never noticed the USA banner is hidden on mobile 😕

**Comment by pwolfert** [comment]
Created a new ticket to solve the banner issue: https://jira.cms.gov/browse/WNMGDS-2293. I spent five minutes trying to fix it just now and couldn't, so I'm moving on since it's out of scope.

**Comment by pwolfert** [comment]
VRTs failed on a couple of the reset stories for an unknown reason. I restarted the tests to see if it's just an intermittent failure

**Pull request merged**
