### PR TITLE
[WNMGDS-1243] Add Storybook stories for Pagination

### PR DESCRIPTION
**Pull request by forrestbaer**
### Summary
Added a storybook story for the Pagination component

### Added
Default Pagination
Pagination with hidden next/prev on extremities
Compact Pagination

### How to test
run `yarn storybook` and see the new pagination stories, play with args to confirm they update

### CODE REVIEW

**Review by pwolfert — APPROVED** [review]
Works great 👍 The `currentPage` control doesn't seem to sync perfectly, but it doesn't really matter because all the functionality is there, and it doesn't produce unintended behavior. It's probably Storybook's problem.

**Review by scheul93 — APPROVED** [review]
Looks good! Nice use of args!

**Comment by forrestbaer** [comment]
Oh thats an easy fix @pwolfert , just needed to set it to 1 in useargs, fixed!

**Comment by forrestbaer** [comment]
Oh wait nevermind, I see what you're saying, yeah something to investigate.. I guess strings don't update like other controls for some reason.

**Pull request merged**
