### PR TITLE
Copy wiki pages over to guides directory

### LINKED ISSUE #320: Consider moving wiki pages into a guides folder
## Description
Consider moving the wiki pages into a guides folder to keep documentation in one place as well as have the ability to review, modify, and collaborate on documentation easier. 

Pages can be found here https://github.com/CMSgov/design-system/wiki

### PR DESCRIPTION
**Pull request by line47**
This PR adds wiki pages to a guides folder. No content changes. This closes #320 

- [ ] After this PR is merged add reference links to the new content location from the wiki pages.

### CODE REVIEW

**Comment by line47** [comment]
I think once we have these pages into a place where we can collaborate on reviews and edits we can then look to refine and update as necessary.

**Comment by line47** [comment]
@phiden OK to move forward on this?

**Comment by phiden** [comment]
@line47 go for it

**Comment by line47** [comment]
Can you approve the PR?
We've got a policy for at least one approving review before merging work in 👍

**Pull request merged**
