### PR TITLE
[WNMGDS-1153] stories for Table

### PR DESCRIPTION
**Pull request by scheul93**
## Summary
Adding some storybook stories for the Table component

### Added
* Story for stackable table
* Story for scrollable table
* Story for a multi-header table
Other variations of the component can be achieved through Storybook controls

## How to test
run `yarn storybook` and see the Table stories

### CODE REVIEW

**Comment by pwolfert** [comment]
I haven't figured out why, but the Stackable Table doesn't seem to render the column headings. 

## Storybook
Screen Shot 2021-11-29 at 10 35 20 AM

## Docs site
Screen Shot 2021-11-29 at 10 35 07 AM

**Comment by scheul93** [comment]
> I haven't figured out why, but the Stackable Table doesn't seem to render the column headings.

I think I have some data missing from my stories. I'll update

**Review by forrestbaer — APPROVED** [review]
looks good! 👍

**Review by pwolfert — APPROVED** [review]
LGTM 👍

**Pull request merged**
