### PR TITLE
[WNMGDS-689] Use SVG in react, process SVG in build scripts

### PR DESCRIPTION
**Pull request by bernardwang**
### Summary
- Adds `babel-plugin-inline-react-svg` to allow usage of SVG directly in React components
- Adds `gulp-svgmin` to minimize SVG files as they are copied to `dist`
- Uses `gulp-svgmin` to prettify SVG files in `src`, improve formatting and remove unnecessary attributes and markup
- Update CMSDS scripts to watch assets/scss files slightly more efficiently

### CODE REVIEW

**Review by nichia — COMMENTED** [review]
The svg icons are not showing up on buttons.
Screen Shot 2020-11-06 at 10 26 19 AM

**Comment by nichia** [comment]
hcgov and medicare child design system doc site are showing up but the product app are failing with typescript issues:
```Failed to compile.

/Users/tchutnichia/Code/Support/coverage-tools-frontend/src/components/CCXPDropdown.tsx
TypeScript error in /Users/tchutnichia/Code/Support/coverage-tools-frontend/src/components/CCXPDropdown.tsx(8,10):
Module '"../../../../../../../Users/tchutnichia/Code/Support/coverage-tools-frontend/node_modules/@cmsgov/ds-medicare-gov/dist/types"' has no exported member 'ChoiceList'.  TS2305

     6 |   useRef,
     7 | } from "react";
  >  8 | import { ChoiceList, Button } from "@cmsgov/ds-medicare-gov";
       |          ^
     9 | import { useTranslate } from "../helpers";
    10 | 
    11 | interface CCXPDropdownProps {
^C
➜  coverage-tools-frontend git:(master)


Failed to compile.

/Users/tchutnichia/Code/Support/windowshop/src/components/ErrorRetryAlert/ErrorRetryAlert.tsx
TypeScript error in /Users/tchutnichia/Code/Support/windowshop/src/components/ErrorRetryAlert/ErrorRetryAlert.tsx(4,23):
Could not find a declaration file for module '@cmsgov/ds-healthcare-gov'. '/Users/tchutnichia/Code/Support/windowshop/node_modules/@cmsgov/ds-healthcare-gov/dist/components/index.js' implicitly has an 'any' type.
  Try `npm install @types/cmsgov__ds-healthcare-gov` if it exists or add a new declaration (.d.ts) file containing `declare module '@cmsgov/ds-healthcare-gov';`  TS7016

    2 | import React from "react";
    3 | import capitalize from "pet-shared-components/lib/utils/capitalize";
  > 4 | import { Alert } from "@cmsgov/ds-healthcare-gov";
      |                       ^
    5 | 
    6 | type Props = {
    7 |   onRetry: () => any;
^C
➜  windowshop git:(master)

**Comment by bernardwang** [comment]
> The svg icons are not showing up on buttons.
> Screen Shot 2020-11-06 at 10 26 19 AM

I'm not having this issue, did you make sure to run npm install? This PR updates dependencies

**Comment by nichia** [comment]
If I run `npm install`, `yarn start` ends up with an error message `error Command "cmsds" not found.`.

I've tried setting up the testing with:
- `git clean -fdx`
- `yarn install`
- `yarn start` (also tried `yarn build`)
But not sure why still the svg icon on buttons is still missing. 
The devTools console shows some warning message, but I don't think it's related to the svg change:
`DevTools failed to load SourceMap: Could not load content for chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/injectGlobalHook.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/contentScript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`

**Comment by nichia** [comment]
I can see the svg area, but it's empty 
Screen Shot 2020-11-06 at 1 14 20 PM

**Comment by bernardwang** [comment]
Sorry, when I said `npm install` I meant `yarn install`, we never use npm in this repo. I tried 
```
git clean -fdx
yarn install
yarn start
``` 
but im still not getting that error. @line47 can you try?

**Comment by line47** [comment]
I'm not seeing the icons either. I did notice the path information was not showing when I use the inspector.

Here is a comparison screenshot.
The left is what's live and the right is this branch. 

Screen Shot 2020-11-06 at 3 07 15 PM

**Comment by bernardwang** [comment]
I see, so the problem is only happening for that specific icon. The new gulp task for minifying SVG is some reason clearing the `symbols.svg`, maybe because it is using `symbols` or something? I'll look into it.

I'm also still not getting that console error that @nichia was getting.

**Comment by nichia** [comment]
The console error is resolved - it's due to my chrome devTools setting https://stackoverflow.com/questions/61339968/devtools-failed-to-load-sourcemap-could-not-load-content-for-chrome-extension
We you able to run windowshop or cverage-tools-frontend? I'm currently getting typescript error for those https://github.com/CMSgov/design-system/pull/871#issuecomment-723152387.

**Comment by bernardwang** [comment]
@nichia @line47 the issue should be resolved now

**Review by nichia — COMMENTED** [review]
The changes worked great!
Noticed a couple of things:
- checkmark on Step List has a tiny marking on it, not sure if it's just my screen? 
Screen Shot 2020-11-09 at 3 14 19 PM

- running `yarn test:e2e` is prompting for an update of caniuse-lite  
`Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db`

**Comment by line47** [comment]
This is working for me!

**Review by line47 — APPROVED** [review]

**Review by line47 — APPROVED** [review]

**Comment by nichia** [comment]
Looks like some icons (next.svg and symbols.svg) are still getting cleared out  https://github.com/CMSgov/design-system/pull/871#issuecomment-723308110

**Comment by line47** [comment]
I noticed this with the symbols.svg 
Screen Shot 2020-11-10 at 4 06 10 PM

**Comment by bernardwang** [comment]
@nichia can you show me what you mean?

**Comment by bernardwang** [comment]
> I noticed this with the symbols.svg
> Screen Shot 2020-11-10 at 4 06 10 PM

This has been fixed @line47

**Comment by nichia** [comment]
The next.svg (Button component page) and symbols.svg (Tabs component page) icons are showing up great now.

**Review by nichia — APPROVED** [review]
I removed the Autocomplete extends typedef line and tested on Mgov ds, Hgov ds and the associated products and they work as expected.

**Review by line47 — APPROVED** [review]

**Pull request merged**
