### PR TITLE
[WNMGDS-2235] Fix visual diffs in main

### PR DESCRIPTION
**Pull request by forrestbaer**
## Summary

- Ran `yarn build && yarn test:browser:update` in main and this is what I got.

## How to test

1. Evaluate changes!

## Checklist

- [x] Prefixed the PR title with the [Jira ticket number](https://jira.cms.gov/projects/WNMGDS/) as `[WNMGDS-####] Title` or [NO-TICKET] if this is unticketed work.
- [x] Created or updated unit tests to cover any new or modified code

### CODE REVIEW

**Comment by forrestbaer** [comment]
I think these came with a recent PR and just weren't updated there. @line47 do these look like changes from your recent PR?

**Comment by line47** [comment]
@forrestbaer yes that looks accurate to me. However, I wasn't expecting the error text and icon color on the medicare VRT examples to change colors.

**Comment by pwolfert** [comment]
Uh oh, these visual changes are definitely regressions. I guess I merged that PR to quickly. I wonder why it didn't catch them.

**Comment by pwolfert** [comment]
Oh, these might not be covered in the smoke tests, but they should have shown up in the nightly build

**Comment by pwolfert** [comment]
In https://github.com/CMSgov/design-system/pull/2394, medicare's `error-light` color changed from `crimson-100` to `crimson-300`, and `error-light` is what's used for that inverse error color. We probably want to just change the component theme variables to use `error-lighter`

**Comment by forrestbaer** [comment]
Looking into why the nightly tests didn't pick this up, maybe due to some of my recent interaction changes.

**Comment by line47** [comment]
> In https://github.com/CMSgov/design-system/pull/2394, medicare's error-light color changed from crimson-100 to crimson-300, and error-light is what's used for that inverse error color. We probably want to just change the component theme variables to use error-lighter

Exactly! Thanks @pwolfert

**Comment by forrestbaer** [comment]
I'm working through this mess, there was some bad logic in our test scripts, some old snapshots that shouldn't exist, and the color change. Can hold off on reviewing till I give the go-ahead.

**Comment by forrestbaer** [comment]
Closing this for now, this issue brought up other issues with our VRT that I will resolve in a couple tickets..

**Comment by line47** [comment]
Thanks @forrestbaer !

**Pull request closed without merging**
