### PR TITLE
[WNMGOPS-104] Adding brief document about the new deployment pipeline job

### PR DESCRIPTION
**Pull request by slapula**
### Added
* Adding brief document on how to kick off the new deployment pipeline job in CBJ

### CODE REVIEW

**Comment by line47** [comment]
How does this deployment information pair with the Release process documentation?
https://github.com/CMSgov/design-system/blob/master/guides/RELEASE-PROCESS.md

Could we place all this in a single file?

**Comment by line47** [comment]
☝️ cc @phiden

**Comment by line47** [comment]
👋 Hey @slapula, can we make this documentation as part of this doc? https://github.com/CMSgov/design-system/blob/master/guides/RELEASE-PROCESS.md

**Comment by slapula** [comment]
@line47 Works for me! How does this latest update look?

**Comment by slapula** [comment]
@line47 
1. This job does not replace the current process.  Both are still viable deployment methods.  The job just automates it and makes it a bit more hands-free.
2. You would use the manual process in the case of a CBJ outage or if you wanted more control over the process for any reason.

**Comment by line47** [comment]
Which portions of the deployment process does it automate? `Publish to NPM` and `Update the documentation website`?

**Comment by slapula** [comment]
@line47 It doesn't perform those tasks, no, my job automates Patrick's steps to build the assets with yarn then deploy them to Akamai Netstorage. That's why I initially believed this would warrant a separate document.

**Comment by line47** [comment]
I haven't deployed the CMS Design System yet and I'm not familiar with what Patrick did. 
Are those steps captured in the current `RELEASE-PROCESS.md` documentation? 

Ideally, I'd like this release process doc to be easy to follow if you are doing everything manually or if you are using the automated process in addition to the manual parts.

**Comment by slapula** [comment]
@line47 Not specifically. This is the process that Patrick follows and it's the process we have documented in Confluence.  It concerns build and releasing to Netstorage which I don't see mentioned in that file:
```
1. In the root of the design system's Git directory on your local machine, ensure you are on the master branch and have the latest updates: 
  a. git checkout master && git pull
2. Compile and build the documentation assets:
  a. npm run build
3. Test the documentation site locally to ensure it renders as expected. Open localhost:8001 in your browser after you run the following:
  a. cd docs && python -m SimpleHTTPServer 8001
4. Connect to Akamai NetStorage using SFTP
5. Replace the files in the prod/wwwroot/ NetStorage directory with the files from the design system's docs/ directory on your local machine.
6. Visit design.cms.gov to ensure the changes were successful.
```

**Pull request merged**
