### PR TITLE
[NO-TICKET] Update button migration docs

### PR DESCRIPTION
**Pull request by line47**
## Summary

Updating the button migration page on the documentation site to add details for design and some illustrations about the previous and new button architecture.

## How to test

Run the doc site with `yarn start:gatsby` and visit the migrating to v4 buttons page

### CODE REVIEW

**Comment by pwolfert** [comment]
@line47 I was thinking that because there are actual buttons and then screenshots of buttons, the screenshots would look cleaner in the page if we added a little border around images that are clearly images.

<details>
  <summary>Take a look at this animated before/after gif and let me know what you think</summary>
  
add-image-borders
</details>

**Comment by pwolfert** [comment]
Updated demo: https://cmsgov.github.io/design-system/branch/NO-TICKET-update-button-migration-docs

**Comment by line47** [comment]
LGTM! Thanks @pwolfert !

**Review by forrestbaer — APPROVED** [review]
LGTM 👍🏻

**Review by scheul93 — APPROVED** [review]
Easy to read!

**Pull request merged**
