### PR TITLE
adding text-decoration line-through utility class

### PR DESCRIPTION
**Pull request by carynligon**
**Note:** 
- Add the [Jira ticket number](https://jira.cms.gov/projects/WNMGDS/) to the PR title like this `[WNMGDS-10] - title of pr here` to link to the related issue in Jira.
- You can automatically [close related GitHub issues by using keywords](https://help.github.com/en/articles/closing-issues-using-keywords).
- If your changes involve code please update the snapshots by running `yarn update-snapshots`.

**Please follow the format below and remove any sections that aren't relevant.**

### Added
List new features or components. Include a screenshot for new visual elements.

### Changed
List changes in existing functionality or design. 
If the change was visual, include a comparison screenshot showing the before and after the visual change.

### Deprecated
List once-stable features or components to be deprecated in this PR.

### Removed
List deprecated features or components removed in this PR.

### Fixed
List any bug fixes.

### CODE REVIEW

**Comment by line47** [comment]
Thanks for this @carynligon can you edit the above PR description to add some details and or screenshots of the proposed changes?

**Comment by line47** [comment]
This pr closes #438

**Comment by line47** [comment]
This PR adds a class for the test-decoration `line-through`

### Screenshot 
Screen Shot 2019-10-11 at 3 37 26 PM

**Comment by carynligon** [comment]
@line47 ah SO sorry! My team recently switched to gitlab and I had been completely neglecting my github notifications! Thanks for following up on this!! 🎉

**Pull request merged**
