### PR TITLE
[WNMGDS-1280] Clean up stories using background parameters

### PR DESCRIPTION
**Pull request by forrestbaer**
## Summary
- Moved background parameters into global scope so every story can use them.
- Removed background parameters from individual stories referencing them

## How to test
Run `yarn install && yarn storybook` to fire up storybook and validate all stories have access to the hgov, mgov and light backgrounds in the toolbar above the story.

### CODE REVIEW

**Comment by scheul93** [comment]
I'm also seeing the background param in `ChoiceList.stories`. Is that something that can be cleaned up as part of this branch?

**Comment by forrestbaer** [comment]
> I'm also seeing the background param in `ChoiceList.stories`. Is that something that can be cleaned up as part of this branch? (Not sure if this branch is up-to-date with master)

Good find, happy to!

**Comment by forrestbaer** [comment]
done, ready for review

**Review by scheul93 — APPROVED** [review]
LGTM

**Pull request merged**
