### PR TITLE
[WNMGDS-916] Feature/secondary tertiary buttons (#1106)

### PR DESCRIPTION
**Pull request by pwolfert**
There's only one commit on this even though we cherry-picked two commits into this branch because [the second one](a95cc3773bbf70996d5374ba60264fb73af6ad58) was swallowed up during resolution of merge conflicts.

See #1106 and #1117.

### CODE REVIEW

**Review by scheul93 — APPROVED** [review]
LGTM

**Review by forrestbaer — APPROVED** [review]

**Comment by line47** [comment]
@pwolfert and @scheul93 I was thinking about closing this PR - ok with you all?

**Comment by pwolfert** [comment]
@line47, sorry to say it, but yeah.

**Comment by line47** [comment]
closing as this approach to button work has changed

**Pull request closed without merging**
