### PR TITLE
[WNMGS-437] Move doc files to @cmsgov/design-system-docs

### PR DESCRIPTION
**Pull request by bernardwang**
### Summary
- All doc files (_docs.scss, .example.html, .example.jsx) are moved into @cmsgov/design-system-docs so that all documentation related files are located in one place (with the exception of React props)
- Doc site generation for react props and react examples have been changed to be more explicit, `@react-component` previously would add both react examples and react props, even though there is another tag called `@react-example`. This PR replaces `@react-component` with `@react-props`, which is supplied with the name of the React file where props come from.
- `@hide-example` tag was removed, instead simplify don't specify a `@react-example` tag.

How to test:
- Follow same steps [here](https://github.com/CMSgov/design-system/pull/659)
- For child DS, use this 
[child-design-system-example 2.zip](https://github.com/CMSgov/design-system/files/4548680/child-design-system-example.2.zip)
- Additionally, test the "View source file" links for both core and child DS react files. Note: the links will 404 because the changes arent merged with master yet, but just confirm that they will work

### CODE REVIEW

**Comment by line47** [comment]
@bernardwang is this the link to testing info? 
https://github.com/CMSgov/design-system/pull/659

The link above went to all the closed PRs

**Comment by line47** [comment]
Tested following the instruction here https://github.com/CMSgov/design-system/pull/659

**CMSDS core**
Test the site is reloaded correctly in the following scenarios:

**this is not reloading**
a. React component in design-system is updated 
b. React component prop documentation in design-system is updated
c. HTML and React component examples in design-system are updated

**This is reloading**
d. Documentation content design-system is updated (i.e. .docs.scss file)
e. CSS in design-system is updated
f. React component in design-system-docs is updated
g. CSS in design-system-docs is updated


**Child ds**
Test the site is reloaded correctly in the following scenarios:

**these only get reloaded when the docs.scss page gets modified**
a. React component in design-system is updated 
b. React component prop documentation in design-system is updated
c. HTML and React component examples in design-system are updated

**This is reloading**
d. Documentation content design-system is updated (i.e. .docs.scss file)
e. CSS in design-system is updated

**Comment by bernardwang** [comment]
@line47 The latest commit should address your feedback.

**Comment by line47** [comment]
@bernardwang here is my latest round of testing let me know if you'd like to pair on any of these errors if I haven't given enough details.

#### Core CMSDS:
1. Run `yarn install` ✅ 
2. Run `yarn build` to build `design-system` and `design-system-docs` ✅ 
3. Run `yarn start` to build, serve, and watch files for the doc site ✅ 
4. Test the site is reloaded correctly in the following scenarios:
     a. React component in `design-system` is updated **❌ I get the message "0 Doc pages added to packages/design-system-docs" when updating a component**
     b. React component prop documentation in `design-system` is updated  ✅
     c. HTML and React component examples in `design-system` are updated  ✅
     d. Documentation content `design-system` is updated (i.e. `.docs.scss` file) ✅
     e. CSS in `design-system` is updated ✅
     f. React component in `design-system-docs` is updated ✅
     g. CSS in `design-system-docs` is updated ✅

#### Child DS
2. Run `yarn install` (This will also `npm link` the core ds packages)  ✅ 
2. Run `yarn build` to build `design-system` and `design-system-docs` ✅
3. Run `yarn start` to build, serve, and watch files for the doc site  ✅
4. Test the site is reloaded correctly in the following scenarios:
     a. React component in `design-system` is updated ✅
     b. React component prop documentation in `design-system` is updated ✅
     c. HTML and React component examples in `design-system` are updated  ✅
     d. Documentation content `design-system` is updated (i.e. `.docs.scss` file) ✅
     e. CSS in `design-system` is updated ✅
     f. React component in `design-system-docs` is updated  **❌ I modified the jump to guidance link text in the core and it was not reflected in the child ds after a rebuild of the child ds** 
     g. CSS in `design-system-docs` is updated **❌ I modified the code color to pink in the core and it was not reflected in the child ds after a rebuild of the child ds** 
4. Additionally, test these overrides:
    a. Overriding a core React component and prop docs, ensuring it is outputted in the `dist` (i.e. `src/Button/Button.jsx`) **❌ I modified the default button text to Hello and it was not updated in dist/ Button.js** 
    b. Overriding a core React documentation (i.e. `src/Button/_Button.docs.scss`) ✅
    c. Overriding core DS css (i.e. `src/Button/Button.scss`) ✅
    d. Adding new DS components, documentation and css (i.e. `src/NewBadge`)  ✅
    e. Overriding doc site css (i.e. `docs/example.scss` or `docs/index.scss`) **❌ I updated example.scss and the changes were not reflected **

**Comment by bernardwang** [comment]
@line47 Sorry for the confusion, but I think what I said about child DS testing wasn't correct. 
Since a child DS would normally be using `design-system` and `design-system-docs` from NPM, theres no need to test the scripts rebuilding and reloading the child DS when changes occur in the core packages. The only way to make that work is to add extra `npm link`, but I don't think thats necessary.

All the overrides for Child DS should work however. For 6a, which Button did you update? When I change both the react component code and the react prop docs in `child-design-system-example/src/components/Button/Button.jsx`, I see it reflected in the Button React page on localhost.
For `docs/example.scss` and `docs/index.scss`, updating those should work in my latest commit.

I'm still working on fixing 4a that you tested

**Comment by line47** [comment]
Did another round of testing and everything has passed!

**Comment by nichia** [comment]
Hi Bernard 
Summary: 
- testing of the Core CMSDS & Child DS passed. 
- "view source files" links for core cmsds have the correct new folder structure. 
However, the child ds links is still containing the current folder structure: 
`https://github.com/CMSgov/design-system/blob/master/packages/design-system/src/components/Autocomplete/Autocomplete.jsx`

**Core CMSDS:**
1. Run yarn install ✅
2. Run yarn build to build design-system and design-system-docs ✅
3. Run yarn start to build, serve, and watch files for the doc site ✅
4. Test the site is reloaded correctly in the following scenarios:
  a. React component in design-system is updated ✅
  b. React component prop documentation in design-system is updated ✅
  c. HTML and React component examples in design-system are updated ✅ - in docs
  d. Documentation content design-system is updated (i.e. .docs.scss file) ✅
  e. CSS in design-system is updated  ??
  f. React component in design-system-docs is updated ✅
  g. CSS in design-system-docs is updated ??

**Child DS:**
1. Download and extract
  child-design-system-example .zip ✅
2. Make sure child-design-system-example is in the same directory containing the core CMSDS repo, aka adjacent to the design-system repo folder. ✅
3. Run yarn install (This will also npm link the core ds packages) ✅
4. Go through the same tests listed above for the core CMSDS ✅
  a. React component in design-system is updated ✅
  b. React component prop documentation in design-system is updated ✅
  c. HTML and React component examples in design-system are updated ✅- in docs
  d. Documentation content design-system is updated (i.e. .docs.scss file) ✅
  e. CSS in design-system is updated  ✅- in .scss file
  f. React component in design-system-docs is updated ✅
  g. CSS in design-system-docs is updated ✅- in .scss file

Additionally, test the "View source file" links for both core and child DS react files. - Note: the links will 404 because the changes arent merged with master yet, but just confirm that they will work ✅

**Pull request merged**
