### PR TITLE
[WNMGDS-478] Add USWDS to build scripts

### PR DESCRIPTION
**Pull request by bernardwang**
### Summary
- Adds USWDS as dependency
- Update our build scripts to include USWDS files in imports
- Fixes our stats function in our build scripts to better compare changes in our CSS 

### How to test
- Ensure that USWDS mixins, functions, and variables are available for use.
- Ensure Child DS work as expected
- Ensure our compiled CSS doesn't contain any USWDS code, and has not increased in size from USWDS code

### CODE REVIEW

**Comment by line47** [comment]
I used `@include u-border(2px);` on the `.ds-c-alert` and while it worked it also threw an error saying 
```
[10:12:42] sass Error transpiling Sass!
[10:12:42] packages/design-system/src/styles/components/_Alert.scss
Error: no mixin named u-border
        on line 61 of packages/design-system/src/styles/components/_Alert.scss
        from line 2 of packages/design-system/src/styles/components/index.scss
>>   @include u-border(2px);

   -----------^
```

**Review by line47 — APPROVED** [review]

**Review by nichia — COMMENTED** [review]
USWDS dependency(mixins, functions and variables) are working on the core.
Having difficulties with the child design system build process:
- m.gov child ds `yarn build` error:
```[07:00:09] 📝  83 Doc pages added to ./docs
[07:00:09] sass Error transpiling Sass!
[07:00:09] node_modules/@cmsgov/design-system-docs/src/styles/components/_example.scss
Error: no mixin named u-padding-x
        on line 4 of node_modules/@cmsgov/design-system-docs/src/styles/components/_example.scss
        from line 8 of node_modules/@cmsgov/design-system-docs/src/styles/_example.scss
        from line 7 of docs/src/example.scss
>>   @include u-padding-x($theme-site-margins-mobile-width);

   -----------^
 undefined
[07:00:09] 🚜  Running Webpack statically```


- hc.gov child ds `yarn build` error:
```  --ignoreRootPath  This flag will prevent build files from
                    using `rootPath` while still building for
                    production.    [boolean] [default: false]

TypeError: _react.default.createContext is not a function
    at Object.<anonymous> (/Users/tchutnichia/Code/ds-healthcare-gov/node_modules/react-transition-group/cjs/TransitionGroupContext.js:10:31)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)```

**Review by nichia — APPROVED** [review]
Works on hc.gov child ds after updating the core package.json to have "react-transition-group": "^2.9.0"

Works on child ds adding the following import to index.scss - @import 'uswds/dist/scss/uswds';

**Comment by bernardwang** [comment]
> * Works when I add `@import 'uswds/dist/scss/uswds';` to the child design system to `index.scss`

@line47 @nichia It sounds like theres an issue with the child DS, as we dont want to be doing this import. This would cause the child DS CSS to include all of the USWDS stylesheets, which is not intended. The child DS should have access to USWDS mixins through the core alone

**Comment by bernardwang** [comment]
@line47 @nichia USWDS mixins and functions should be working and avaliable in Child DS's by default now, if either of you can do a quick retest

**Comment by line47** [comment]
I tried earlier today and was getting `Error transpiling Sass!`  - unfortunately, I won't be able to pair until tomorrow on this.

**Comment by nichia** [comment]
On core ds: the uswds tokens works after the `yarn install` and `yarn start`. The mixins and functions works on the child ds too.

But looks like on core ds, `yarn build` right after running `yarn install` is giving this on core.
`[Error: ENOENT: no such file or directory, open '/Users/tchutnichia/Code/design-system/tmp/latestCSS.css'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/tchutnichia/Code/design-system/tmp/latestCSS.css'
}
error Command failed with exit code 1.`

**Comment by bernardwang** [comment]
@line47 I tried to reproduce the issue you mentioned in Slack, but I was able to use the USWDS mixin on the simple footer component
https://gyazo.com/82b922cf32a680095cea9cfae66cf75b
```
.m-c-footer {
  //background-color: $color-gray-lightest;
  background-color: color('accent-cool');
```

**Comment by bernardwang** [comment]
> On core ds: the uswds tokens works after the `yarn install` and `yarn start`. The mixins and functions works on the child ds too.
> 
> But looks like on core ds, `yarn build` right after running `yarn install` is giving this error:
> `[Error: ENOENT: no such file or directory, open '/Users/tchutnichia/Code/design-system/tmp/latestCSS.css'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/Users/tchutnichia/Code/design-system/tmp/latestCSS.css' } error Command failed with exit code 1.`

This should be fixed now.

**Review by line47 — APPROVED** [review]
LGTM! Thanks for the assist Ni!

**Comment by nichia** [comment]
Works great!

**Review by nichia — APPROVED** [review]

**Pull request merged**
