### PR TITLE
[WNMGDS-716] Convert TextField and Select to typescript

### PR DESCRIPTION
**Pull request by kimieann**
Updated TextField and Select components to typescript

## How to test
Instructions on how to test the changes. This is not exhaustive list of ways you should test this PR.
http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-716/convert-textfield-select-to-typescript

- Review doc pages for TextField and Select and compare to existing doc site. Make sure there are no mismatches
- Test TextField and Select in create-react-app and create-react-app-typescript and make sure behavior is as expected

### CODE REVIEW

**Review by nichia — COMMENTED** [review]
Taking a quick look:
- Dropdown props on doc site: some of the props are missing from the `Dropdown` props page eg. className, children, defaultValue, disabled, id, onBlur, onChange... etc. It does have a `ref` prop, which was not on the previous react props table
- Text field props on doc site: some missing props like the case with Dropdown

**Comment by nichia** [comment]
Core DS:
- `yarn test:e2e` has Month Picker failing - not sure why as this pr doesn't affect it?
- need to manually run `yarn lint` to apply formatting with prettier and Eslint checking

Hgov DS worked

Mgov DS:
-  build error  -  typedef file: `mgov-design-system/node_modules/@cmsgov/design-system/dist/types/TextField/Mask"  has no exported member 'unmaskValue'. `

**Comment by kimieann** [comment]
@nichia - Issues should be fixed now.

**Review by nichia — COMMENTED** [review]
It works on core cmsds and Hcgov DS. However, testing on Mgov DS gives an error of `dist/types/TextField/Mask"' has no exported member 'unmaskValue'.`

**Comment by nichia** [comment]
Ah, we probably can remove the following from `src/types/index.d.ts` and add them to below line 40 (// Type definitions generated by cmsds scripts):
export { default as Dropdown } from './Dropdown/Dropdown';
export { default as Select } from './Dropdown/Select';
export { default as TextField } from './TextField/TextField';
export { default as TextInput } from './TextField/TextInput';
export { maskValue, unmaskValue } from './TextField/Mask';

**Comment by nichia** [comment]
@kimieann - after updating `src/types/index.d.ts` - Mgov DS throws below error: 
```
@cmsgov/design-system/dist/types/index.d.ts(39,1): error TS2308: Module './Dropdown/Select' has already exported a member named 'OmitProps'. Consider explicitly re-exporting to resolve the ambiguity.
TypeScript: 1 semantic error
```

**Comment by kimieann** [comment]
@nichia - Can you see if the mgov errors are fixed now

**Review by nichia — APPROVED** [review]
Tested on Mgov and it’s working as expected :rocket:

**Review by line47 — APPROVED** [review]
This is working for me, thanks!

**Pull request merged**
